apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flowconfigurations.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sources:
                  type: array
                  items:
                    type: string
                destinations:
                  type: array
                  items:
                    type: string
                resources:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
  scope: Namespaced
  names:
    plural: flowconfigurations
    singular: flowconfiguration
    kind: FlowConfiguration
    shortNames:
    - fc
