CREATE TABLE IF NOT EXISTS messages (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS saga_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  trace_id CHAR(36) NOT NULL,
  step VARCHAR(64) NOT NULL,
  status ENUM('PENDING','SUCCESS','FAILURE') NOT NULL,
  error_code VARCHAR(64),
  error_detail TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  idempotency_key CHAR(36) PRIMARY KEY,
  processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_status ENUM('SUCCESS','FAILURE') NOT NULL,
  trace_id CHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS outbox (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  aggregate_key VARCHAR(128) NOT NULL,
  topic VARCHAR(128) NOT NULL,
  payload JSON NOT NULL,
  headers JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dispatched BOOLEAN DEFAULT FALSE
);