apiVersion: v1
kind: ConfigMap
metadata:
  name: saga-grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    {
      "apiVersion": 1,
      "datasources": [
        {
          "name": "Loki",
          "type": "loki",
          "access": "proxy",
          "url": "http://loki:3100",
          "isDefault": false,
          "editable": true,
          "jsonData": {
            "maxLines": 1000
          }
        },
        {
          "name": "Jaeger",
          "type": "jaeger",
          "access": "proxy",
          "url": "http://jaeger-query:16686",
          "editable": true
        }
      ]
    }
