apiVersion: apps/v1
kind: Deployment
metadata:
  name: step5
spec:
  replicas: 1
  selector:
    matchLabels: { app: step5 }
  template:
    metadata:
      labels: { app: step5 }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: step5
        image: saga/step5:dev
        imagePullPolicy: IfNotPresent
        ports: [{containerPort: 8080, name: metrics}]
        env:
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: GROUP_ID
          value: "svc5-group"
        - name: TOPIC_IN
          value: "saga.step4.completed"
        - name: TOPIC_OUT
          value: "saga.step5.completed"
        - name: DLQ_TOPIC
          value: "saga.dlq"
        - name: STEP
          value: "5"
        - name: JAEGER_COLLECTOR
          value: "http://jaeger-collector:14268/api/traces"
        - name: FAIL_MODE
          value: "retryable"

        readinessProbe:
          httpGet: { path: /metrics, port: 8080 }
          initialDelaySeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: step5
  labels:
    app: step5
    saga-metrics: "true"
spec:
  selector: { app: step5 }
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
