repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'go fmt ./...'
        language: system
        pass_filenames: false
      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c '$(go env GOPATH)/bin/golangci-lint run'
        language: system
        pass_filenames: false
      - id: go-test-quick
        name: go test (quick)
        entry: bash -c 'go test ./...'
        language: system
        pass_filenames: false
